---
- hosts: 172.31.34.50
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: install webservers
    apt:
      name: apache2
      state: present
      
  - name: start webservers
    service:
      name: apache2
      state: started
      