---
- hosts: webservers
  become: yes
  tasks:
  - name : install java8 on ubuntu
    apt:
      name: "{{javaonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"

  - name: install java8 on rehat
    yum:
      name: "{{javaonRedhat}}"
      state: present
    when: ansible_os_family =="RedHat"